version: "3"

services:
  web:
    image: nginx
    container_name: nginx.exam
    volumes:
      - "./app:/app"
      - "./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./Nginx/htpasswd:/etc/nginx/htpasswd"
    ports:
      - 80:80
    links:
      - php

  php:
    build:
      context: ./PHP
      dockerfile: DockerfilePhp
    container_name: php.exam
    volumes:
      - "./app:/app"
    links:
      - db

  db:
    image: postgres
    container_name: db.exam
    restart: always
    volumes:
      - "./Postgres/1-schema.sql:/docker-entrypoint-initdb.d/init.sql"

