parameters:
    upload_path: '%kernel.project_dir%%env(resolve:UPLOAD_FILES_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    App\Services\EntityManager:
        arguments: ['@doctrine.orm.entity_manager']